### ISSUE TITLE
Window looks weird after exiting full screen.

### ISSUE THREAD

**Issue by Nuklusone** [BonBon-exchange/bonbon-browser#326]
## Expected Behavior
<img width="1440" alt="Screenshot 2022-08-02 at 13 13 38" src="https://user-images.githubusercontent.com/110396886/182361519-d182ba03-a8d0-477c-8bbe-58115daf8ff2.png">

## Current Behavior
<img width="1440" alt="Screenshot 2022-08-02 at 13 10 56" src="https://user-images.githubusercontent.com/110396886/182361256-3463fe90-b920-441f-bb6e-b4d3b65828e9.png">

## Steps to Reproduce

1. Open a video and full screen it

2. exit full sreen mode

3. (doesn't happen all the time. After repeating step 1 and 2 a couple of times it will happen.

**Comment by dcallus** [comment]
[Nuklusone](https://github.com/Nuklusone) Please spend a little bit more time writing up your issues.  What are we supposed to be looking at here?

Window looks weird is not a good description. Use arrows or something on your pics or be a little bit more descriptive. I honestly can't tell what I'm supposed to be look here? It looks like it's just scrolled down a bit further to me, which obviously can't happen if that window is maximised but I have no way of knowing if it's maximised due to the fact we don't have separate max/min icons yet and you haven't provided much info.

**Comment by danielfebrero** [comment]
I think what we have to look here is in the second screenshot, there is 10px of whitespace added all around the browserview.

**Comment by Nuklusone** [comment]
@dcallus my bad, for me it was pretty clear what was wrong. But that's probably because I made the issue. I'll mark some things on the image and update the issue
